spring:
  datasource:
    url: jdbc:mysql://localhost:3306/explorer?serverTimezone=UTC&allowMultiQueries=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password:
    initialization-mode: always